import 'recommendation_text_utils.dart';

class IngredientAliasUtils {
  const IngredientAliasUtils._();

  static const Map<String, Set<String>> _groups = {
    'bo': {
      'bo',
      'thit_bo',
      'xuong_bo',
      'gan_bo',
      'bo_vien',
      'noi_tang_bo',
      'beef',
    },
    'heo': {
      'heo',
      'lon',
      'thit_heo',
      'thit_lon',
      'bi_heo',
      'mo_heo',
      'suon_heo',
      'xuong_heo',
      'noi_tang_heo',
      'noi_tang_lon',
      'pork',
    },
    'ga': {
      'ga',
      'thit_ga',
      'long_ga',
      'trung_ga',
      'xuong_ga',
      'chicken',
    },
    'vit': {
      'vit',
      'thit_vit',
      'trung_vit',
      'trung_vit_lon',
      'long_vit',
      'duck',
    },
    'hai_san': {
      'hai_san',
      'tom',
      'cua',
      'muc',
      'ngheu',
      'ngao',
      'so',
      'oc',
      'ca',
      'mam_tom',
      'mam_ca',
      'seafood',
      'shrimp',
      'crab',
      'squid',
      'fish',
    },
    'ca': {
      'ca',
      'ca_loc',
      'ca_ro',
      'ca_hoi',
      'ca_thu',
      'ca_basa',
      'ca_ngu',
      'fish',
    },
    'tom': {
      'tom',
      'tom_tuoi',
      'tom_kho',
      'tom_su',
      'tom_dat',
      'shrimp',
    },
    'cua_ghe': {
      'cua',
      'ghe',
      'thit_cua',
      'gach_cua',
      'crab',
    },
    'muc': {
      'muc',
      'muc_tuoi',
      'muc_kho',
      'squid',
    },
    'oc_so_ngheu': {
      'oc',
      'so',
      'ngheu',
      'ngao',
      'hen',
      'trai',
      'shellfish',
    },
    'sua': {
      'sua',
      'sua_bo',
      'kem',
      'pho_mai',
      'bo_sua',
      'milk',
      'cheese',
      'cream',
    },
    'dau_phong': {
      'dau_phong',
      'lac',
      'bo_dau_phong',
      'peanut',
    },
    'dau_nanh': {
      'dau_nanh',
      'dau_tuong',
      'sua_dau_nanh',
      'tau_hu',
      'dau_hu',
      'tofu',
      'soy',
    },
    'me': {
      'me',
      'hat_me',
      'dau_me',
      'sesame',
    },
    'hat_dieu': {
      'hat_dieu',
      'dieu',
      'cashew',
    },
    'hanh': {
      'hanh',
      'hanh_la',
      'hanh_tay',
      'hanh_tim',
      'hanh_kho',
      'hanh_phi',
      'cu_hanh',
      'cu_hanh_tim',
      'onion',
      'red_onion',
      'shallot',
      'scallion',
      'spring_onion',
    },
    'toi': {
      'toi',
      'cu_toi',
      'toi_phi',
      'garlic',
    },
    'ot': {
      'ot',
      'ot_tuoi',
      'ot_kho',
      'ot_bot',
      'sa_te',
      'chili',
      'chilli',
    },
    'tieu': {
      'tieu',
      'hat_tieu',
      'tieu_den',
      'tieu_xanh',
      'pepper',
    },
    'gung': {
      'gung',
      'cu_gung',
      'ginger',
    },
    'sa': {
      'sa',
      'cay_sa',
      'lemongrass',
    },
    'rieng': {
      'rieng',
      'cu_rieng',
      'galangal',
    },
    'nghe': {
      'nghe',
      'bot_nghe',
      'cu_nghe',
      'turmeric',
    },
    'chanh': {
      'chanh',
      'nuoc_cot_chanh',
      'lime',
      'lemon',
    },
    'me_chua': {
      'me_chua',
      'me_vat',
      'nuoc_me',
      'tamarind',
    },
    'gia_vi_pho': {
      'que',
      'vo_que',
      'hoa_hoi',
      'dai_hoi',
      'thao_qua',
      'dinh_huong',
      'cinnamon',
      'star_anise',
      'cardamom',
      'clove',
    },
    'la_chanh': {
      'la_chanh',
      'lime_leaf',
      'kaffir_lime_leaf',
    },
    'rau_mui': {
      'rau_mui',
      'ngo',
      'ngo_ri',
      'mui_ta',
      'rau_ngo',
      'cilantro',
      'coriander',
    },
    'ngo_gai': {
      'ngo_gai',
      'mui_tau',
      'sawtooth_herb',
      'culantro',
    },
    'rau_ram': {
      'rau_ram',
      'vietnamese_coriander',
    },
    'hung_que': {
      'hung_que',
      'rau_hung',
      'basil',
    },
    'tia_to': {
      'tia_to',
      'perilla',
    },
    'la_lot': {
      'la_lot',
      'piper_lolot',
    },
    'diep_ca': {
      'diep_ca',
      'rau_diep_ca',
      'fish_mint',
      'fish_leaf',
    },
    'kinh_gioi': {
      'kinh_gioi',
      'vietnamese_balm',
    },
    'thi_la': {
      'thi_la',
      'rau_thi_la',
      'dill',
    },
    'he': {
      'he',
      'bong_he',
      'la_he',
      'garlic_chive',
      'chive',
    },
    'rau_thom': {
      'rau_thom',
      'rau_song',
      'rau_mui',
      'ngo_gai',
      'rau_ram',
      'hung_que',
      'tia_to',
      'la_lot',
      'diep_ca',
      'kinh_gioi',
      'thi_la',
      'he',
    },
    'gia_do': {
      'gia',
      'gia_do',
      'bean_sprout',
      'bean_sprouts',
    },
    'rau_muong': {
      'rau_muong',
      'water_spinach',
      'morning_glory',
    },
    'bap_cai': {
      'bap_cai',
      'cai_bap',
      'cabbage',
    },
    'cai_thao': {
      'cai_thao',
      'napa_cabbage',
    },
    'cai_xanh': {
      'cai_xanh',
      'cai_be_xanh',
      'mustard_green',
    },
    'mang': {
      'mang',
      'mang_tuoi',
      'mang_kho',
      'bamboo_shoot',
    },
    'nam': {
      'nam',
      'nam_rom',
      'nam_huong',
      'nam_meo',
      'moc_nhi',
      'mushroom',
    },
    'trung': {
      'trung',
      'trung_ga',
      'trung_vit',
      'trung_cut',
      'egg',
    },
    'gluten': {
      'gluten',
      'bot_mi',
      'mi_can',
      'banh_mi',
      'mi',
      'mi_vang',
      'mi_trung',
      'hoanh_thanh',
      'wheat',
    },
    'gao': {
      'gao',
      'com',
      'com_tam',
      'com_nep',
      'xoi',
      'chao',
      'bun',
      'pho',
      'banh_pho',
      'hu_tieu',
      'mi_quang',
      'banh_canh',
      'banh_hoi',
      'banh_da',
      'banh_trang',
      'bot_gao',
      'bot_nep',
      'rice',
      'rice_noodle',
    },
    'mien': {
      'mien',
      'bun_tau',
      'mien_dong',
      'glass_noodle',
      'cellophane_noodle',
    },
    'khoai': {
      'khoai',
      'khoai_tay',
      'khoai_lang',
      'khoai_mon',
      'potato',
      'sweet_potato',
      'taro',
    },
    'bap': {
      'bap',
      'ngo_bap',
      'bap_my',
      'corn',
    },
    'nuoc_mam': {
      'nuoc_mam',
      'mam',
      'mam_ca',
      'fish_sauce',
    },
    'mam_tom': {
      'mam_tom',
      'shrimp_paste',
    },
    'mam_nem': {
      'mam_nem',
      'fermented_fish_sauce',
    },
    'tuong': {
      'tuong',
      'tuong_den',
      'tuong_ot',
      'tuong_an_pho',
      'hoisin',
      'chili_sauce',
    },
    'xi_dau': {
      'xi_dau',
      'nuoc_tuong',
      'soy_sauce',
    },
    'giam': {
      'giam',
      'giam_gao',
      'rice_vinegar',
      'vinegar',
    },
    'muoi': {
      'muoi',
      'muoi_tieu',
      'salt',
    },
    'bot_ngot': {
      'bot_ngot',
      'mi_chinh',
      'msg',
    },
    'hat_nem': {
      'hat_nem',
      'bot_nem',
      'seasoning_powder',
    },
    'dua_chua': {
      'dua_chua',
      'do_chua',
      'cai_chua',
      'kim_chi',
      'fermented_vegetable',
    },
    'cu_cai': {
      'cu_cai',
      'cu_cai_trang',
      'cu_cai_do',
      'do_chua',
      'daikon',
      'radish',
    },
    'ca_rot': {
      'ca_rot',
      'carrot',
    },
    'du_du': {
      'du_du',
      'du_du_xanh',
      'papaya',
      'green_papaya',
    },
    'chuoi_xanh': {
      'chuoi_xanh',
      'chuoi_chat',
      'green_banana',
    },
    'khe': {
      'khe',
      'starfruit',
    },
    'dua_leo': {
      'dua_leo',
      'dua_chuot',
      'cucumber',
    },
    'ca_chua': {
      'ca_chua',
      'tomato',
    },
    'dua': {
      'dua',
      'nuoc_cot_dua',
      'cot_dua',
      'coconut',
      'coconut_milk',
    },
    'dau_phu': {
      'dau_phu',
      'dau_hu',
      'tau_hu',
      'tofu',
    },
    'cha_lua': {
      'cha_lua',
      'gio_lua',
      'gio',
      'vietnamese_pork_roll',
    },
    'cha_ca': {
      'cha_ca',
      'ca_vien',
      'fish_cake',
      'fish_ball',
    },
    'pate': {
      'pate',
      'pa_te',
      'pork_liver_pate',
    },
    'ruoc': {
      'ruoc',
      'cha_bong',
      'thit_cha_bong',
      'pork_floss',
    },
    'lap_xuong': {
      'lap_xuong',
      'lap_suon',
      'chinese_sausage',
    },
    'da_heo': {
      'da_heo',
      'bi_heo',
      'pork_skin',
    },
    'banh_phong_tom': {
      'banh_phong_tom',
      'phong_tom',
      'shrimp_cracker',
    },
    'mo_hanh': {
      'mo_hanh',
      'dau_hanh',
      'hanh_phi',
      'scallion_oil',
      'fried_shallot',
    },
    'dua_bao': {
      'dua_bao',
      'dua_soi',
      'coconut_flake',
      'shredded_coconut',
    },
    'duong': {
      'duong',
      'duong_cat',
      'duong_phen',
      'mat_ong',
      'sugar',
      'honey',
    },
    'dau_mo': {
      'dau_an',
      'dau_mo',
      'mo_heo',
      'dau_thuc_vat',
      'oil',
      'fat',
    },
    'dau_dieu': {
      'dau_dieu',
      'hat_dieu_mau',
      'annatto_oil',
      'annatto',
    },
    'noi_tang': {
      'noi_tang',
      'long',
      'gan',
      'tim',
      'phoi',
      'bao_tu',
      'long_heo',
      'long_bo',
      'organ_meat',
    },
  };

  static Set<String> expand(Iterable<String> values) {
    final result = <String>{};

    for (final value in values) {
      final normalized = RecommendationTextUtils.normalizeToken(value);
      if (normalized.isEmpty) continue;

      final matchingGroup = _findGroup(normalized);
      if (matchingGroup != null) {
        result.addAll(matchingGroup);
      } else {
        result.add(normalized);
      }
    }

    return result;
  }

  static Set<String>? _findGroup(String value) {
    for (final group in _groups.values) {
      if (group.contains(value)) return group;
    }
    return null;
  }
}
