import 'recommendation_text_utils.dart';

class IngredientAliasUtils {
  const IngredientAliasUtils._();

  static const Map<String, Set<String>> _groups = {
    'bo': {
      'bo',
      'thit_bo',
      'xuong_bo',
      'gan_bo',
      'bo_vien',
      'noi_tang_bo',
      'beef',
    },
    'heo': {
      'heo',
      'lon',
      'thit_heo',
      'thit_lon',
      'bi_heo',
      'mo_heo',
      'suon_heo',
      'xuong_heo',
      'noi_tang_heo',
      'noi_tang_lon',
      'pork',
    },
    'ga': {'ga', 'thit_ga', 'long_ga', 'trung_ga', 'xuong_ga', 'chicken'},
    'vit': {
      'vit',
      'thit_vit',
      'trung_vit',
      'trung_vit_lon',
      'long_vit',
      'duck',
    },
    'hai_san': {
      'hai_san',
      'tom',
      'cua',
      'muc',
      'ngheu',
      'ngao',
      'so',
      'oc',
      'ca',
      'mam_tom',
      'mam_ca',
      'seafood',
      'shrimp',
      'crab',
      'squid',
      'fish',
    },
    'ca': {
      'ca',
      'ca_loc',
      'ca_ro',
      'ca_hoi',
      'ca_thu',
      'ca_basa',
      'ca_ngu',
      'fish',
    },
    'tom': {'tom', 'tom_tuoi', 'tom_kho', 'tom_su', 'tom_dat', 'shrimp'},
    'cua_ghe': {'cua', 'ghe', 'thit_cua', 'gach_cua', 'crab'},
    'muc': {'muc', 'muc_tuoi', 'muc_kho', 'squid'},
    'oc_so_ngheu': {'oc', 'so', 'ngheu', 'ngao', 'hen', 'trai', 'shellfish'},
    'sua': {
      'sua',
      'sua_bo',
      'kem',
      'pho_mai',
      'bo_sua',
      'milk',
      'cheese',
      'cream',
    },
    'dau_phong': {'dau_phong', 'lac', 'bo_dau_phong', 'peanut'},
    'dau_nanh': {
      'dau_nanh',
      'dau_tuong',
      'sua_dau_nanh',
      'tau_hu',
      'dau_hu',
      'tofu',
      'soy',
    },
    'me': {'me', 'hat_me', 'dau_me', 'sesame'},
    'hat_dieu': {'hat_dieu', 'dieu', 'cashew'},
    'hanh': {
      'hanh',
      'hanh_la',
      'hanh_tay',
      'hanh_tim',
      'hanh_kho',
      'hanh_phi',
      'cu_hanh',
      'cu_hanh_tim',
      'onion',
      'red_onion',
      'shallot',
      'scallion',
      'spring_onion',
    },
    'toi': {'toi', 'cu_toi', 'toi_phi', 'garlic'},
    'ot': {'ot', 'ot_tuoi', 'ot_kho', 'ot_bot', 'sa_te', 'chili', 'chilli'},
    'tieu': {'tieu', 'hat_tieu', 'tieu_den', 'tieu_xanh', 'pepper'},
    'gung': {'gung', 'cu_gung', 'ginger'},
    'sa': {'sa', 'cay_sa', 'lemongrass'},
    'rieng': {'rieng', 'cu_rieng', 'galangal'},
    'nghe': {'nghe', 'bot_nghe', 'cu_nghe', 'turmeric'},
    'chanh': {'chanh', 'nuoc_cot_chanh', 'lime', 'lemon'},
    'me_chua': {'me_chua', 'me_vat', 'nuoc_me', 'tamarind'},
    'gia_vi_pho': {
      'que',
      'vo_que',
      'hoa_hoi',
      'dai_hoi',
      'thao_qua',
      'dinh_huong',
      'cinnamon',
      'star_anise',
      'cardamom',
      'clove',
    },
    'la_chanh': {'la_chanh', 'lime_leaf', 'kaffir_lime_leaf'},
    'rau_mui': {
      'rau_mui',
      'ngo',
      'ngo_ri',
      'mui_ta',
      'rau_ngo',
      'cilantro',
      'coriander',
    },
    'ngo_gai': {'ngo_gai', 'mui_tau', 'sawtooth_herb', 'culantro'},
    'rau_ram': {'rau_ram', 'vietnamese_coriander'},
    'hung_que': {'hung_que', 'rau_hung', 'basil'},
    'tia_to': {'tia_to', 'perilla'},
    'la_lot': {'la_lot', 'piper_lolot'},
    'diep_ca': {'diep_ca', 'rau_diep_ca', 'fish_mint', 'fish_leaf'},
    'kinh_gioi': {'kinh_gioi', 'vietnamese_balm'},
    'thi_la': {'thi_la', 'rau_thi_la', 'dill'},
    'he': {'he', 'bong_he', 'la_he', 'garlic_chive', 'chive'},
    'rau_thom': {
      'rau_thom',
      'rau_song',
      'rau_mui',
      'ngo_gai',
      'rau_ram',
      'hung_que',
      'tia_to',
      'la_lot',
      'diep_ca',
      'kinh_gioi',
      'thi_la',
      'he',
    },
    'gia_do': {'gia', 'gia_do', 'bean_sprout', 'bean_sprouts'},
    'rau_muong': {'rau_muong', 'water_spinach', 'morning_glory'},
    'bap_cai': {'bap_cai', 'cai_bap', 'cabbage'},
    'cai_thao': {'cai_thao', 'napa_cabbage'},
    'cai_xanh': {'cai_xanh', 'cai_be_xanh', 'mustard_green'},
    'mang': {'mang', 'mang_tuoi', 'mang_kho', 'bamboo_shoot'},
    'nam': {'nam', 'nam_rom', 'nam_huong', 'nam_meo', 'moc_nhi', 'mushroom'},
    'trung': {'trung', 'trung_ga', 'trung_vit', 'trung_cut', 'egg'},
    'gluten': {
      'gluten',
      'bot_mi',
      'mi_can',
      'banh_mi',
      'mi',
      'mi_vang',
      'mi_trung',
      'hoanh_thanh',
      'wheat',
    },
    'gao': {
      'gao',
      'com',
      'com_tam',
      'com_nep',
      'xoi',
      'chao',
      'bun',
      'pho',
      'banh_pho',
      'hu_tieu',
      'mi_quang',
      'banh_canh',
      'banh_hoi',
      'banh_da',
      'banh_trang',
      'bot_gao',
      'bot_nep',
      'rice',
      'rice_noodle',
    },
    'mien': {
      'mien',
      'bun_tau',
      'mien_dong',
      'glass_noodle',
      'cellophane_noodle',
    },
    'khoai': {
      'khoai',
      'khoai_tay',
      'khoai_lang',
      'khoai_mon',
      'potato',
      'sweet_potato',
      'taro',
    },
    'bap': {'bap', 'ngo_bap', 'bap_my', 'corn'},
    'nuoc_mam': {'nuoc_mam', 'mam', 'mam_ca', 'fish_sauce'},
    'mam_tom': {'mam_tom', 'shrimp_paste'},
    'mam_nem': {'mam_nem', 'fermented_fish_sauce'},
    'tuong': {
      'tuong',
      'tuong_den',
      'tuong_ot',
      'tuong_an_pho',
      'hoisin',
      'chili_sauce',
    },
    'xi_dau': {'xi_dau', 'nuoc_tuong', 'soy_sauce'},
    'giam': {'giam', 'giam_gao', 'rice_vinegar', 'vinegar'},
    'muoi': {'muoi', 'muoi_tieu', 'salt'},
    'bot_ngot': {'bot_ngot', 'mi_chinh', 'msg'},
    'hat_nem': {'hat_nem', 'bot_nem', 'seasoning_powder'},
    'dua_chua': {
      'dua_chua',
      'do_chua',
      'cai_chua',
      'kim_chi',
      'fermented_vegetable',
    },
    'cu_cai': {
      'cu_cai',
      'cu_cai_trang',
      'cu_cai_do',
      'do_chua',
      'daikon',
      'radish',
    },
    'ca_rot': {'ca_rot', 'carrot'},
    'du_du': {'du_du', 'du_du_xanh', 'papaya', 'green_papaya'},
    'chuoi_xanh': {'chuoi_xanh', 'chuoi_chat', 'green_banana'},
    'khe': {'khe', 'starfruit'},
    'dua_leo': {'dua_leo', 'dua_chuot', 'cucumber'},
    'ca_chua': {'ca_chua', 'tomato'},
    'dua': {'dua', 'nuoc_cot_dua', 'cot_dua', 'coconut', 'coconut_milk'},
    'dau_phu': {'dau_phu', 'dau_hu', 'tau_hu', 'tofu'},
    'cha_lua': {'cha_lua', 'gio_lua', 'gio', 'vietnamese_pork_roll'},
    'cha_ca': {'cha_ca', 'ca_vien', 'fish_cake', 'fish_ball'},
    'pate': {'pate', 'pa_te', 'pork_liver_pate'},
    'ruoc': {'ruoc', 'cha_bong', 'thit_cha_bong', 'pork_floss'},
    'lap_xuong': {'lap_xuong', 'lap_suon', 'chinese_sausage'},
    'da_heo': {'da_heo', 'bi_heo', 'pork_skin'},
    'banh_phong_tom': {'banh_phong_tom', 'phong_tom', 'shrimp_cracker'},
    'mo_hanh': {
      'mo_hanh',
      'dau_hanh',
      'hanh_phi',
      'scallion_oil',
      'fried_shallot',
    },
    'dua_bao': {'dua_bao', 'dua_soi', 'coconut_flake', 'shredded_coconut'},
    'duong': {'duong', 'duong_cat', 'duong_phen', 'mat_ong', 'sugar', 'honey'},
    'dau_mo': {'dau_an', 'dau_mo', 'mo_heo', 'dau_thuc_vat', 'oil', 'fat'},
    'dau_dieu': {'dau_dieu', 'hat_dieu_mau', 'annatto_oil', 'annatto'},
    'noi_tang': {
      'noi_tang',
      'long',
      'gan',
      'tim',
      'phoi',
      'bao_tu',
      'long_heo',
      'long_bo',
      'organ_meat',
    },
    'de': {'de', 'thit_de', 'de_nui', 'goat', 'goat_meat'},
    'trau': {'trau', 'thit_trau', 'buffalo', 'buffalo_meat'},
    'cuu': {'cuu', 'thit_cuu', 'lamb', 'mutton'},
    'tho': {'tho', 'thit_tho', 'rabbit'},
    'chim': {
      'chim',
      'thit_chim',
      'chim_cau',
      'bo_cau',
      'chim_cut',
      'cut',
      'pigeon',
      'quail',
    },
    'ech': {'ech', 'thit_ech', 'frog'},
    'luon': {'luon', 'thit_luon', 'eel'},
    'chach': {'chach', 'ca_chach', 'loach'},
    'ba_ba': {'ba_ba', 'thit_ba_ba', 'softshell_turtle'},
    'ca_hoi': {'ca_hoi', 'salmon'},
    'ca_ngu': {'ca_ngu', 'tuna'},
    'ca_thu': {'ca_thu', 'mackerel'},
    'ca_com': {'ca_com', 'anchovy'},
    'ca_trich': {'ca_trich', 'herring'},
    'ca_basa': {'ca_basa', 'ca_tra', 'pangasius'},
    'ca_loc': {'ca_loc', 'ca_qua', 'snakehead_fish'},
    'ca_ro': {'ca_ro', 'ca_ro_dong', 'perch'},
    'ca_chep': {'ca_chep', 'carp'},
    'ca_dieu_hong': {'ca_dieu_hong', 'ca_ro_phi', 'tilapia'},
    'ca_keo': {'ca_keo', 'goby'},
    'ghe': {'ghe', 'thit_ghe', 'blue_crab'},
    'so_diep': {'so_diep', 'coi_so_diep', 'scallop'},
    'hau': {'hau', 'hau_sua', 'oyster'},
    'ngao_ngheu': {'ngao', 'ngheu', 'clam'},
    'hen': {'hen', 'thit_hen', 'basket_clam'},
    'bach_tuoc': {'bach_tuoc', 'octopus'},
    'sua_dac': {
      'sua_dac',
      'sua_dac_co_duong',
      'condensed_milk',
    },
    'sua_chua': {'sua_chua', 'yaourt', 'yogurt', 'yoghurt'},
    'pho_mai': {'pho_mai', 'cheese'},
    'bo_sua': {'bo_sua', 'butter'},
    'kem_sua': {'kem_sua', 'whipping_cream', 'heavy_cream', 'cream'},
    'hanh_nhan': {'hanh_nhan', 'almond'},
    'oc_cho': {'hat_oc_cho', 'oc_cho', 'walnut'},
    'hat_de': {'hat_de', 'chestnut'},
    'hat_dac': {'hat_dac', 'palm_seed'},
    'hat_sen': {'hat_sen', 'sen', 'lotus_seed'},
    'hat_bi': {'hat_bi', 'pumpkin_seed'},
    'hat_huong_duong': {'hat_huong_duong', 'sunflower_seed'},
    'mac_ca': {'mac_ca', 'macca', 'macadamia'},
    'ho_de_cuoi': {'ho_de_cuoi', 'pistachio'},
    'dau_xanh': {'dau_xanh', 'do_xanh', 'mung_bean'},
    'dau_den': {'dau_den', 'black_bean'},
    'dau_do': {'dau_do', 'red_bean', 'adzuki_bean'},
    'dau_trang': {'dau_trang', 'white_bean'},
    'dau_ha_lan': {'dau_ha_lan', 'pea', 'green_pea'},
    'dau_co_ve': {'dau_co_ve', 'dau_que', 'green_bean'},
    'dau_bap': {'dau_bap', 'okra'},
    'dau_lentil': {'dau_lentil', 'dau_lang', 'lentil'},
    'lua_mi': {
      'lua_mi',
      'bot_mi',
      'bot_lua_mi',
      'wheat',
      'wheat_flour',
      'flour',
    },
    'yen_mach': {'yen_mach', 'oat', 'oats', 'oatmeal'},
    'lua_mach': {'lua_mach', 'barley'},
    'ngo': {'ngo', 'bap', 'bap_my', 'corn', 'maize'},
    'nep': {'nep', 'gao_nep', 'xoi', 'sticky_rice', 'glutinous_rice'},
    'bun': {'bun', 'bun_tuoi', 'bun_kho', 'rice_vermicelli'},
    'pho': {'pho', 'banh_pho', 'pho_kho', 'rice_noodle'},
    'hu_tieu': {'hu_tieu', 'banh_hu_tieu', 'rice_noodle'},
    'banh_canh': {'banh_canh', 'bot_banh_canh', 'thick_noodle'},
    'mi': {'mi', 'mi_soi', 'mi_trung', 'mi_vang', 'noodle', 'egg_noodle'},
    'rau_ngot': {'rau_ngot', 'katuk'},
    'rau_den': {'rau_den', 'amaranth'},
    'mong_toi': {'mong_toi', 'malabar_spinach'},
    'cai_ngot': {'cai_ngot', 'choy_sum'},
    'cai_thia': {'cai_thia', 'bok_choy', 'pak_choi'},
    'cai_xoong': {'cai_xoong', 'xa_lach_xoong', 'watercress'},
    'xa_lach': {'xa_lach', 'salad', 'lettuce'},
    'bi_do': {'bi_do', 'bi_ngo', 'pumpkin'},
    'bi_dao': {'bi_dao', 'winter_melon'},
    'muop': {'muop', 'muop_huong', 'luffa'},
    'bau': {'bau', 'bau_qua', 'bottle_gourd'},
    'kho_qua': {'kho_qua', 'muop_dang', 'bitter_melon'},
    'ca_tim': {'ca_tim', 'eggplant', 'aubergine'},
    'su_su': {'su_su', 'chayote'},
    'cu_san': {'cu_san', 'cu_dau', 'jicama'},
    'khoai_mon': {'khoai_mon', 'taro'},
    'khoai_lang': {'khoai_lang', 'sweet_potato'},
    'khoai_tay': {'khoai_tay', 'potato'},
    'san': {'san', 'khoai_mi', 'cassava', 'tapioca'},
    'sen': {'sen', 'cu_sen', 'ngo_sen', 'lotus_root'},
    'bong_bi': {'bong_bi', 'hoa_bi', 'pumpkin_flower'},
    'bong_thien_ly': {'bong_thien_ly', 'hoa_thien_ly', 'tonkin_jasmine'},
    'chuoi': {'chuoi', 'banana'},
    'xoai': {'xoai', 'mango'},
    'dua_hau': {'dua_hau', 'watermelon'},
    'thom': {'thom', 'khom', 'pineapple'},
    'mit': {'mit', 'jackfruit'},
    'sau_rieng': {'sau_rieng', 'durian'},
    'bo_trai': {'qua_bo', 'trai_bo', 'avocado'},
    'cam_quyt': {'cam', 'quyt', 'orange', 'mandarin'},
    'buoi': {'buoi', 'pomelo', 'grapefruit'},
    'vai_nhan': {'vai', 'nhan', 'lychee', 'longan'},
    'mam_ruoc': {'mam_ruoc', 'ruoc_tom', 'fermented_shrimp_paste'},
    'chao': {'chao', 'chao_do', 'chao_trang', 'fermented_tofu'},
    'tuong_ban': {'tuong_ban', 'tuong_hat', 'fermented_soybean'},
    'dau_hao': {'dau_hao', 'oyster_sauce'},
    'dau_me': {'dau_me', 'dau_vung', 'sesame_oil'},
    'mayonnaise': {'mayonnaise', 'sot_mayo', 'mayo'},
    'ruou': {'ruou', 'ruou_trang', 'ruou_nep', 'alcohol', 'rice_wine'},
    'bia': {'bia', 'beer'},
    'ca_phe': {'ca_phe', 'coffee'},
    'tra': {'tra', 'che_xanh', 'tea', 'green_tea'},
  };

  static Set<String> expand(Iterable<String> values) {
    final result = <String>{};

    for (final value in values) {
      final normalized = RecommendationTextUtils.normalizeToken(value);
      if (normalized.isEmpty) continue;

      final matchingGroup = _findGroup(normalized);
      if (matchingGroup != null) {
        result.addAll(matchingGroup);
      } else {
        result.add(normalized);
      }
    }

    return result;
  }

  /// Quy nguyên liệu của món về mã nhóm cụ thể nhất. Khác với [expand], hàm
  /// này không bung một nguyên liệu thành toàn bộ họ hàng của nó; nhờ vậy
  /// "bún" không làm "cơm" bị nhận nhầm chỉ vì cùng thuộc nhóm gạo.
  static Set<String> canonicalizeDishIngredients(Iterable<String> values) {
    final result = <String>{};
    for (final value in values) {
      final normalized = RecommendationTextUtils.normalizeToken(value);
      if (normalized.isEmpty) continue;
      final entry = _findGroupEntry(normalized);
      result.add(entry?.key ?? normalized);
    }
    return result;
  }

  static Set<String>? _findGroup(String value) {
    return _findGroupEntry(value)?.value;
  }

  static MapEntry<String, Set<String>>? _findGroupEntry(String value) {
    // Ưu tiên nhóm có mã đúng bằng giá trị người dùng chọn. Ví dụ "cá" phải
    // vào nhóm cá, không bị nhóm "hải sản" rộng hơn bắt trước.
    final exactGroup = _groups[value];
    if (exactGroup != null) return MapEntry(value, exactGroup);

    // Một bí danh có thể nằm trong nhiều nhóm. Chọn nhóm cụ thể nhất (ít phần
    // tử nhất); nhóm tổng quát vẫn hoạt động khi người dùng chọn đúng mã nhóm.
    MapEntry<String, Set<String>>? bestMatch;
    for (final entry in _groups.entries) {
      final group = entry.value;
      if (!group.contains(value)) continue;
      if (bestMatch == null || group.length < bestMatch.value.length) {
        bestMatch = entry;
      }
    }
    return bestMatch;
  }
}
